assignment2/aerojobs2/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

    //home page set
    Route::get('/', array('as'=>'home', 'uses'=> 'JobController@index'));
    //set login and logout routes as well as user store
    Route::post('user/login', array('as' => 'user.login', 'uses' =>       'UserController@login'));
    Route::post('user/store', array('as' => 'user.store', 'uses' =>       'UserController@store'));
    Route::get('user/logout', array('as' => 'user.logout', 'uses' => 'UserController@logout'));
    //get users profile
    Route::get('user/seeker/profile/{id}', array('as' => 'user.seeker.profile', 'uses' => 'UserController@profile'));
    Route::get('job/list', array('as' => 'job.list', 'uses' => 'JobController@listall'));
    Route::get('job/delete', array('as' => 'job.delete', 'uses' => 'JobController@delete'));
    Route::get('employer/all', array('as' => 'employer.all', 'uses' => 'EmployerController@index'));
    Route::get('employer/applications/{id}/{employer_id}', array('as' => 'employer.applications', 'uses' => 'EmployerController@applications'));
    Route::get('job/apply/{id}', array('as' => 'job.apply', 'uses' => 'JobController@apply'));
    Route::post('job/apply/store', array('as' => 'job.apply.store', 'uses' =>         'JobController@application_store'));
    Route::get('job/search/', array('as' => 'job.search', 'uses' =>       'JobController@search'));
    Route::get('user/seeker/create', array('as' => 'user.seeker.create', 'uses' => 'UserController@create_seeker'));
    Route::get('user/employer/create', array('as' => 'user.employer.create', 'uses' => 'UserController@create_employer'));

    //register controllers
    Route::resource('docs', 'HomeController@docs');
    Route::resource('user', 'UserController');
    Route::resource('job', 'JobController');
    Route::resource('employer', 'EmployerController');

  

assignment2/aerojobs2/app/models/Employer.php
<?php
use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableInterface;
class Employer extends Eloquent
{
  public function user()
    {
        return $this->hasOne('user');
    }
  
  public function job()
    {
        return $this->hasMany('job');
    }
  
   public function application()
    {
        return $this->hasMany('application');
    }

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'employers';

   public static $rules = array(
 'company' => 'required|unique:employers',
 'industry' => 'required',
 'description' => 'required|min:5'
);
}

assignment2/aerojobs2/app/controllers/EmployerController.php
<?php

class EmployerController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
    //return a list of employers
		$employers = Employer::paginate(10);
    //get employers user details
    return View::make('employer.all', compact('employers'));
	}
  
	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
    //return a list of employers jobs
     $job = Job::where('employer_id', '=', $id)->get();
     return View::make('employer.show', compact('job'))->With('employer_id', $id);
}
  
  public function applications($id, $employer_id)
  { 
    //seelect the user who applied for the aplication as well as its details
    $applications = DB::select("Select u.*, a.application_letter, a.application_date From jobs as j, users as u, applications as a Where j.id = ? And a.job_id = ? and j.id= a.job_id and u.id = a.seeker_id and j.employer_id = ?", array($id, $id, $employer_id));
    //return view
    //paginate results
    $applications = Paginator::make($applications, count($applications), 10);
    return View::make('employer.applications', compact('applications'))->With('employer_id', $employer_id);
  }
}

assignment2/aerojobs2/app/views/employer/all.blade.php
@extends('../layout')
@section('title')
All Employers| Aero Jobs - The place for jobs!
@stop
@section('body')
<h3>All Employers</h3>
{{ $employers->links()}}
 @foreach ($employers as $employer)
  <h4>{{{ $employer->company }}}</h4>
<ul class="list-group">
  <li class="list-group-item">Industry: {{{ $employer->industry }}}</li>
  <li class="list-group-item">Description: {{{ $employer->description }}}</li>
  <li class="list-group-item">{{ link_to_route('employer.show','Employers Jobs', array($employer->id)) }}</li>
</ul>
<br/>
  @endforeach
{{ $employers->links()}}
@stop

assignment2/aerojobs2/app/views/employer/applications.blade.php
@extends('../layout')
@section('title')
Applications | Aero Jobs - The place for jobs!
@stop
@section('body')

@if (Auth::check())
@if(Auth::user()->employer_id == $employer_id)
{{ $applications->links() }}
<h2>Applications</h2>
@foreach($applications as $app)
<h4>Application from {{{$app->full_name}}}</h4>
<ul class="list-group">
   <li class="list-group-item">{{ link_to_route('user.seeker.profile','Users Profile', array($app->id)) }}</li>
   <li class="list-group-item">Application Letter: {{{$app->application_letter}}}</li>
   <li class="list-group-item">Application Date/Time: {{{$app->application_date}}}</li>  
</ul>
@endforeach
{{ $applications->links() }}
@else
<p>You are not authorized to view this page</p>
@endif
@endif
@stop

assignment2/aerojobs2/app/views/employer/show.blade.php
@extends('../layout')
@section('title')
Employer| Aero Jobs - The place for jobs!
@stop
@section('body')
@if (Auth::check())
@if(Auth::user()->employer_id == $employer_id)
<p>{{ link_to_route('job.create', 'Create a Job') }}</p>
@endif
@endif
@foreach ($job as $j)
<ul class="list-group">
   <li class="list-group-item"><h4>{{ link_to_route('job.show',$j->title, array($j->id)) }}</h4></li>
  <li class="list-group-item">Location: {{{ $j->location }}}</li>
  <li class="list-group-item">Salary: {{{ $j->salary }}}</li>
  <li class="list-group-item">Start Date: {{{ $j->start_date }}}</li>
  <li class="list-group-item">End Date: {{{ $j->end_date }}}</li>
  <li class="list-group-item">{{ link_to_route('job.show','More details', array($j->id)) }}</li>
</ul>
<br/>
  @endforeach
@stop